## Estimating the Total Risk of a Stock II

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("../data/fb_price.csv")
df = df[['Date', 'Adj Close']]
df = df.rename(columns={'Date': 'date',
                        'Adj Close': 'price_t'})
df['returns'] = df['price_t'].pct_change(1)
df.head()

         date    price_t   returns
0  2012-05-18  38.230000       NaN
1  2012-05-21  34.029999 -0.109861
2  2012-05-22  31.000000 -0.089039
3  2012-05-23  32.000000  0.032258
4  2012-05-24  33.029999  0.032187

In [19]:
#ddof to do 1/(n+1) instead of 1/(n+0)
var_fb = np.var(df['returns'], ddof=1)
print(var_fb)

0.000546801751575295

In [20]:
sd_fb = np.sqrt(var_fb)
print(sd_fb)

0.023383792497695812

In [21]:
print(np.std(df['returns'], ddof=1))

0.023383792497695812

In [22]:
df.head()

         date    price_t   returns
0  2012-05-18  38.230000       NaN
1  2012-05-21  34.029999 -0.109861
2  2012-05-22  31.000000 -0.089039
3  2012-05-23  32.000000  0.032258
4  2012-05-24  33.029999  0.032187

In [23]:
df['deviations'] = df['returns'] - df['returns'].mean()
df.head()

         date    price_t   returns  deviations
0  2012-05-18  38.230000       NaN         NaN
1  2012-05-21  34.029999 -0.109861   -0.111211
2  2012-05-22  31.000000 -0.089039   -0.090389
3  2012-05-23  32.000000  0.032258    0.030909
4  2012-05-24  33.029999  0.032187    0.030838

In [24]:
df['squared_deviations'] = df['deviations'] ** 2
df.head()

         date    price_t   returns  deviations  squared_deviations
0  2012-05-18  38.230000       NaN         NaN                 NaN
1  2012-05-21  34.029999 -0.109861   -0.111211            0.012368
2  2012-05-22  31.000000 -0.089039   -0.090389            0.008170
3  2012-05-23  32.000000  0.032258    0.030909            0.000955
4  2012-05-24  33.029999  0.032187    0.030838            0.000951

In [25]:
#sum(df['squared_deviations'].dropna())
print(np.sum(df['squared_deviations'])) #drops the nans by default

0.7720840732243166

In [26]:
ssd = np.sum(df['squared_deviations'])
var_fb_manual =  ssd / (len(df['squared_deviations'].dropna()) - 1)
print(var_fb_manual, var_fb_manual == var_fb)

0.000546801751575295 True

In [27]:
sd_fb_manual = np.sqrt(var_fb_manual)
print(sd_fb_manual, sd_fb_manual == sd_fb)

0.023383792497695812 True

In [28]:
sd_fb_annual = sd_fb * np.sqrt(250)
print(sd_fb_annual)

0.3697302231273821

In [31]:
returns_annual_crude = df['returns'].mean() * 250
print(returns_annual_crude)

0.33736546468750195

In [32]:
returns_annual_soph = ((1 + df['returns'].mean()) ** 250) - 1
print(returns_annual_soph)

0.40093243279785296

In [ ]:
#we almost always want investments with higher returns than the risk