## Solving Puzzles

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/15stocks_price.csv')
df.set_index('date_gsheets', inplace=True)

In [3]:
returns = df.pct_change(1).dropna()

In [4]:
corr_matrix = returns.corr().round(2)

In [5]:
corr_matrix

,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA,MA,AMZN,MSFT,UN,V
AAPL,1.00,0.21,0.12,0.31,0.27,0.26,0.17,0.17,0.26,0.20,0.35,0.26,0.33,0.25,0.30
KO,0.21,1.00,0.09,0.47,0.37,0.32,0.37,0.31,0.35,0.14,0.36,0.23,0.32,0.41,0.33
NFLX,0.12,0.09,1.00,0.19,0.15,0.12,0.04,0.10,0.16,0.23,0.25,0.30,0.21,0.15,0.22
BRK.B,0.31,0.47,0.19,1.00,0.54,0.48,0.42,0.33,0.55,0.22,0.53,0.33,0.43,0.42,0.50
DIS,0.27,0.37,0.15,0.54,1.00,0.34,0.34,0.27,0.43,0.23,0.43,0.31,0.35,0.33,0.41
IBM,0.26,0.32,0.12,0.48,0.34,1.00,0.30,0.23,0.43,0.18,0.38,0.23,0.39,0.30,0.36
VZ,0.17,0.37,0.04,0.42,0.34,0.30,1.00,0.29,0.37,0.11,0.28,0.17,0.29,0.31,0.27
WMT,0.17,0.31,0.10,0.33,0.27,0.23,0.29,1.00,0.24,0.11,0.25,0.14,0.22,0.23,0.25
GE,0.26,0.35,0.16,0.55,0.43,0.43,0.37,0.24,1.00,0.19,0.40,0.26,0.34,0.33,0.38
TSLA,0.20,0.14,0.23,0.22,0.23,0.18,0.11,0.11,0.19,1.00,0.27,0.26,0.21,0.18,0.23
MA,0.35,0.36,0.25,0.53,0.43,0.38,0.28,0.25,0.40,0.27,1.00,0.44,0.43,0.37,0.77
AMZN,0.26,0.23,0.30,0.33,0.31,0.23,0.17,0.14,0.26,0.26,0.44,1.00,0.37,0.23,0.40
MSFT,0.33,0.32,0.21,0.43,0.35,0.39,0.29,0.22,0.34,0.21,0.43,0.37,1.00,0.32,0.41
UN,0.25,0.41,0.15,0.42,0.33,0.30,0.31,0.23,0.33,0.18,0.37,0.23,0.32,1.00,0.34
V,0.30,0.33,0.22,0.50,0.41,0.36,0.27,0.25,0.38,0.23,0.77,0.40,0.41,0.34,1.00

In [6]:
corr_matrix[['NFLX','TSLA']]

       NFLX  TSLA
AAPL   0.12  0.20
KO     0.09  0.14
NFLX   1.00  0.23
BRK.B  0.19  0.22
DIS    0.15  0.23
IBM    0.12  0.18
VZ     0.04  0.11
WMT    0.10  0.11
GE     0.16  0.19
TSLA   0.23  1.00
MA     0.25  0.27
AMZN   0.30  0.26
MSFT   0.21  0.21
UN     0.15  0.18
V      0.22  0.23

In [7]:
corr_matrix[['AAPL','MA','MSFT']]

       AAPL    MA  MSFT
AAPL   1.00  0.35  0.33
KO     0.21  0.36  0.32
NFLX   0.12  0.25  0.21
BRK.B  0.31  0.53  0.43
DIS    0.27  0.43  0.35
IBM    0.26  0.38  0.39
VZ     0.17  0.28  0.29
WMT    0.17  0.25  0.22
GE     0.26  0.40  0.34
TSLA   0.20  0.27  0.21
MA     0.35  1.00  0.43
AMZN   0.26  0.44  0.37
MSFT   0.33  0.43  1.00
UN     0.25  0.37  0.32
V      0.30  0.77  0.41

In [8]:
corr_matrix[['KO','BRK.B']]

         KO  BRK.B
AAPL   0.21   0.31
KO     1.00   0.47
NFLX   0.09   0.19
BRK.B  0.47   1.00
DIS    0.37   0.54
IBM    0.32   0.48
VZ     0.37   0.42
WMT    0.31   0.33
GE     0.35   0.55
TSLA   0.14   0.22
MA     0.36   0.53
AMZN   0.23   0.33
MSFT   0.32   0.43
UN     0.41   0.42
V      0.33   0.50